### ISSUE TITLE
The Market Maker is crashing when it can't get the data from the EV charging post

### ISSUE THREAD

**Issue by rethore** [WeOU/svalinhub#1]
```bash
Error getting the car charger data
name 'data_charger' is not defined
Traceback (most recent call last):
  File "marketmaker.py", line 677, in <module>
    mm.step()
  File "marketmaker.py", line 368, in step
    'imp_car': self.imp_car,
AttributeError: 'MarketMaker' object has no attribute 'imp_car'
````

**Comment by rethore** [comment]
- [ ] Check that the MM has access to the EVC API
- [ ] Figure out a fail safe way to address the disconnection issues
